const barColors = { dark: '#595959', medium: '#7F7F7F', moderate: '#A5A5A5', light: '#CCCCCC', lightGray: '#E7ECEF', moderateGray: '#C5C3C6', heavyGray: '#8B8C89', heavyBlue: '#274C77', moderateBlue: '#6096BA', lightBlue: '#A3CEF1' }

const wCodes = [
    { code: 0, barColor: barColors.lightGray, description: "Clear Sky", aka: "Clear", themeNight: "https://res.cloudinary.com/dmjhwxcjh/image/upload/v1680059195/weather/theme_night_clear_vnjrvb.jpg", themeDay: "https://res.cloudinary.com/dmjhwxcjh/image/upload/v1680056770/weather/theme_clear_sunny_nsxqs2.jpg", dayIcon: "https://res.cloudinary.com/dmjhwxcjh/image/upload/v1678575906/weather/clear_day_m2t2o2.svg", nightIcon: "https://res.cloudinary.com/dmjhwxcjh/image/upload/v1678575906/weather/clear_night_cmf1uv.svg" },
    { code: 1, barColor: barColors.lightGray, description: "Mainly Clear", aka: "Clear", themeNight: "https://res.cloudinary.com/dmjhwxcjh/image/upload/v1680059195/weather/theme_night_clear_vnjrvb.jpg", themeDay: "https://res.cloudinary.com/dmjhwxcjh/image/upload/v1680056770/weather/theme_clear_sunny_nsxqs2.jpg", dayIcon: "https://res.cloudinary.com/dmjhwxcjh/image/upload/v1678575906/weather/clear_day_m2t2o2.svg", nightIcon: "https://res.cloudinary.com/dmjhwxcjh/image/upload/v1678575906/weather/clear_night_cmf1uv.svg" },
    { code: 2, barColor: barColors.moderateGray, description: "Partly Cloudy", aka: "Partly Cloudy", themeNight: "https://res.cloudinary.com/dmjhwxcjh/image/upload/v1680059196/weather/theme_night_partly_cloudy_ikiswd.jpg", themeDay: "https://res.cloudinary.com/dmjhwxcjh/image/upload/v1680054813/weather/theme_partly_cloudy_crqkcs.jpg", dayIcon: "https://res.cloudinary.com/dmjhwxcjh/image/upload/v1678575906/weather/cloudy_partly_day_vpe1hu.svg", nightIcon: "https://res.cloudinary.com/dmjhwxcjh/image/upload/v1678575906/weather/cloudy_partly_night_rrm86p.svg" },
    { code: 3, barColor: barColors.moderateGray, description: "Overcast", aka: "Overcast", themeNight: "https://res.cloudinary.com/dmjhwxcjh/image/upload/v1680059195/weather/theme_night_overcast_kixacb.jpg", themeDay: "https://res.cloudinary.com/dmjhwxcjh/image/upload/v1680054812/weather/theme_overcast_tsfmre.jpg", dayIcon: "https://res.cloudinary.com/dmjhwxcjh/image/upload/v1678575906/weather/cloudy_partly_day_vpe1hu.svg", nightIcon: "https://res.cloudinary.com/dmjhwxcjh/image/upload/v1678575906/weather/cloudy_partly_night_rrm86p.svg" },
    { code: 45, barColor: barColors.heavyGray, description: "Fog", aka: "Fog", themeNight: "https://res.cloudinary.com/dmjhwxcjh/image/upload/v1680059195/weather/theme_night_foggy_e6dsmd.jpg", themeDay: "https://res.cloudinary.com/dmjhwxcjh/image/upload/v1680054813/weather/theme_fog_lpgmli.jpg", dayIcon: "https://res.cloudinary.com/dmjhwxcjh/image/upload/v1678575907/weather/fog_cloudy_mrruyh.svg", nightIcon: "https://res.cloudinary.com/dmjhwxcjh/image/upload/v1678575907/weather/fog_cloudy_mrruyh.svg" },
    { code: 48, barColor: barColors.heavyGray, description: "Depositing Rime Fog", aka: "Freezing Fog", themeNight: "https://res.cloudinary.com/dmjhwxcjh/image/upload/v1680059195/weather/theme_night_foggy_e6dsmd.jpg", themeDay: "https://res.cloudinary.com/dmjhwxcjh/image/upload/v1680054813/weather/theme_fog_lpgmli.jpg", dayIcon: "https://res.cloudinary.com/dmjhwxcjh/image/upload/v1678575907/weather/fog_l251d9.svg", nightIcon: "https://res.cloudinary.com/dmjhwxcjh/image/upload/v1678575907/weather/fog_l251d9.svg" },
    { code: 51, barColor: barColors.lightBlue, description: "Drizzle: Light", aka: "Light Drizzle", themeNight: "https://res.cloudinary.com/dmjhwxcjh/image/upload/v1680059195/weather/theme_night_drizzle_ooiyej.jpg", themeDay: "https://res.cloudinary.com/dmjhwxcjh/image/upload/v1680054812/weather/theme_drizzle_uieqrg.jpg", dayIcon: "https://res.cloudinary.com/dmjhwxcjh/image/upload/v1678575907/weather/drizzle_xohqvp.svg", nightIcon: "https://res.cloudinary.com/dmjhwxcjh/image/upload/v1678575907/weather/drizzle_xohqvp.svg" },
    { code: 53, barColor: barColors.lightBlue, description: "Drizzle: Moderate", aka: "Drizzle", themeNight: "https://res.cloudinary.com/dmjhwxcjh/image/upload/v1680059195/weather/theme_night_drizzle_ooiyej.jpg", themeDay: "https://res.cloudinary.com/dmjhwxcjh/image/upload/v1680054812/weather/theme_drizzle_uieqrg.jpg", dayIcon: "https://res.cloudinary.com/dmjhwxcjh/image/upload/v1678575907/weather/drizzle_xohqvp.svg", nightIcon: "https://res.cloudinary.com/dmjhwxcjh/image/upload/v1678575907/weather/drizzle_xohqvp.svg" },
    { code: 55, barColor: barColors.moderateBlue, description: "Drizzle: Dense", aka: "Dense Drizzle", themeNight: "https://res.cloudinary.com/dmjhwxcjh/image/upload/v1680059195/weather/theme_night_drizzle_ooiyej.jpg", themeDay: "https://res.cloudinary.com/dmjhwxcjh/image/upload/v1680054812/weather/theme_drizzle_uieqrg.jpg", dayIcon: "https://res.cloudinary.com/dmjhwxcjh/image/upload/v1678575907/weather/drizzle_xohqvp.svg", nightIcon: "https://res.cloudinary.com/dmjhwxcjh/image/upload/v1678575907/weather/drizzle_xohqvp.svg" },
    { code: 56, barColor: barColors.lightBlue, description: "Freezing Drizzle: Light", aka: "Freezing Drizzle", themeNight: "https://res.cloudinary.com/dmjhwxcjh/image/upload/v1680059195/weather/theme_night_drizzle_ooiyej.jpg", themeDay: "https://res.cloudinary.com/dmjhwxcjh/image/upload/v1680054812/weather/theme_drizzle_uieqrg.jpg", dayIcon: "https://res.cloudinary.com/dmjhwxcjh/image/upload/v1678575907/weather/drizzle_xohqvp.svg", nightIcon: "https://res.cloudinary.com/dmjhwxcjh/image/upload/v1678575907/weather/drizzle_xohqvp.svg" },
    { code: 57, barColor: barColors.lightBlue, description: "Freezing Drizzle: Dense", aka: "Freezing Drizzle", themeNight: "https://res.cloudinary.com/dmjhwxcjh/image/upload/v1680059195/weather/theme_night_drizzle_ooiyej.jpg", themeDay: "https://res.cloudinary.com/dmjhwxcjh/image/upload/v1680054812/weather/theme_drizzle_uieqrg.jpg", dayIcon: "https://res.cloudinary.com/dmjhwxcjh/image/upload/v1678575907/weather/drizzle_xohqvp.svg", nightIcon: "https://res.cloudinary.com/dmjhwxcjh/image/upload/v1678575907/weather/drizzle_xohqvp.svg" },
    { code: 61, barColor: barColors.lightBlue, description: "Rain: Slight", aka: "Light Rain", themeNight: "https://res.cloudinary.com/dmjhwxcjh/image/upload/v1680059196/weather/theme_night_light_rain_fpokbo.jpg", themeDay: "https://res.cloudinary.com/dmjhwxcjh/image/upload/v1680054813/weather/theme_light_rain_dtyukx.jpg", dayIcon: "https://res.cloudinary.com/dmjhwxcjh/image/upload/v1678575908/weather/rain_aztazw.svg", nightIcon: "https://res.cloudinary.com/dmjhwxcjh/image/upload/v1678575908/weather/rain_aztazw.svg" },
    { code: 63, barColor: barColors.moderateBlue, description: "Rain: Moderate", aka: "Rain", themeNight: "https://res.cloudinary.com/dmjhwxcjh/image/upload/v1680059196/weather/theme_night_light_rain_fpokbo.jpg", themeDay: "https://res.cloudinary.com/dmjhwxcjh/image/upload/v1680054813/weather/theme_light_rain_dtyukx.jpg", dayIcon: "https://res.cloudinary.com/dmjhwxcjh/image/upload/v1678575908/weather/rain_aztazw.svg", nightIcon: "https://res.cloudinary.com/dmjhwxcjh/image/upload/v1678575908/weather/rain_aztazw.svg" },
    { code: 65, barColor: barColors.heavyBlue, description: "Rain: Heavy", aka: "Heavy Rain", themeNight: "https://res.cloudinary.com/dmjhwxcjh/image/upload/v1680054813/weather/theme_heavy_rain_uxyfaq.jpg", themeDay: "https://res.cloudinary.com/dmjhwxcjh/image/upload/v1680054813/weather/theme_heavy_rain_uxyfaq.jpg", dayIcon: "https://res.cloudinary.com/dmjhwxcjh/image/upload/v1678575908/weather/rain_aztazw.svg", nightIcon: "https://res.cloudinary.com/dmjhwxcjh/image/upload/v1678575908/weather/rain_aztazw.svg" },
    { code: 66, barColor: barColors.moderateBlue, description: "Freezing Rain: Light", aka: "Freezing Rain", themeNight: "https://res.cloudinary.com/dmjhwxcjh/image/upload/v1680059196/weather/theme_night_light_rain_fpokbo.jpg", themeDay: "https://res.cloudinary.com/dmjhwxcjh/image/upload/v1680054813/weather/theme_light_rain_dtyukx.jpg", dayIcon: "https://res.cloudinary.com/dmjhwxcjh/image/upload/v1678575908/weather/rain_aztazw.svg", nightIcon: "https://res.cloudinary.com/dmjhwxcjh/image/upload/v1678575908/weather/rain_aztazw.svg" },
    { code: 67, barColor: barColors.heavyBlue, description: "Freezing Rain: Heavy", aka: "Freezing Rain", themeNight: "https://res.cloudinary.com/dmjhwxcjh/image/upload/v1680054813/weather/theme_heavy_rain_uxyfaq.jpg", themeDay: "https://res.cloudinary.com/dmjhwxcjh/image/upload/v1680054813/weather/theme_heavy_rain_uxyfaq.jpg", dayIcon: "https://res.cloudinary.com/dmjhwxcjh/image/upload/v1678575908/weather/rain_aztazw.svg", nightIcon: "https://res.cloudinary.com/dmjhwxcjh/image/upload/v1678575908/weather/rain_aztazw.svg" },
    { code: 71, barColor: barColors.lightBlue, description: "Snow Fall: Slight", aka: "Light Snow", themeNight: "https://res.cloudinary.com/dmjhwxcjh/image/upload/v1680054813/weather/theme_snow_i63d8t.jpg", themeDay: "https://res.cloudinary.com/dmjhwxcjh/image/upload/v1680054813/weather/theme_snow_i63d8t.jpg", dayIcon: "https://res.cloudinary.com/dmjhwxcjh/image/upload/v1678575909/weather/snow_light_f2kvid.svg", nightIcon: "https://res.cloudinary.com/dmjhwxcjh/image/upload/v1678575909/weather/snow_light_f2kvid.svg" },
    { code: 73, barColor: barColors.moderateBlue, description: "Snow Fall: Moderate", aka: "Snow", themeNight: "https://res.cloudinary.com/dmjhwxcjh/image/upload/v1680054813/weather/theme_snow_i63d8t.jpg", themeDay: "https://res.cloudinary.com/dmjhwxcjh/image/upload/v1680054813/weather/theme_snow_i63d8t.jpg", dayIcon: "https://res.cloudinary.com/dmjhwxcjh/image/upload/v1678575909/weather/snow_moderate_mtavja.svg", nightIcon: "https://res.cloudinary.com/dmjhwxcjh/image/upload/v1678575909/weather/snow_moderate_mtavja.svg" },
    { code: 75, barColor: barColors.heavyBlue, description: "Snow Fall: Heavy", aka: "Heavy Snow", themeNight: "https://res.cloudinary.com/dmjhwxcjh/image/upload/v1680054813/weather/theme_snow_i63d8t.jpg", themeDay: "https://res.cloudinary.com/dmjhwxcjh/image/upload/v1680054813/weather/theme_snow_i63d8t.jpg", dayIcon: "https://res.cloudinary.com/dmjhwxcjh/image/upload/v1678575908/weather/snow_heavy_iny69s.svg", nightIcon: "https://res.cloudinary.com/dmjhwxcjh/image/upload/v1678575908/weather/snow_heavy_iny69s.svg" },
    { code: 77, barColor: barColors.moderateBlue, description: "Snow Grains", aka: "Snow Grains", themeNight: "https://res.cloudinary.com/dmjhwxcjh/image/upload/v1680054813/weather/theme_snow_i63d8t.jpg", themeDay: "https://res.cloudinary.com/dmjhwxcjh/image/upload/v1680054813/weather/theme_snow_i63d8t.jpg", dayIcon: "https://res.cloudinary.com/dmjhwxcjh/image/upload/v1678575908/weather/snow_heavy_iny69s.svg", nightIcon: "https://res.cloudinary.com/dmjhwxcjh/image/upload/v1678575908/weather/snow_heavy_iny69s.svg" },
    { code: 80, barColor: barColors.lightBlue, description: "Rain Showers: Slight", aka: "Light Showers", themeNight: "https://res.cloudinary.com/dmjhwxcjh/image/upload/v1680059196/weather/theme_night_light_rain_fpokbo.jpg", themeDay: "https://res.cloudinary.com/dmjhwxcjh/image/upload/v1680054813/weather/theme_light_rain_dtyukx.jpg", dayIcon: "https://res.cloudinary.com/dmjhwxcjh/image/upload/v1678575908/weather/rain_aztazw.svg", nightIcon: "https://res.cloudinary.com/dmjhwxcjh/image/upload/v1678575908/weather/rain_aztazw.svg" },
    { code: 81, barColor: barColors.moderateBlue, description: "Rain Showers: Moderate", aka: "Showers", themeNight: "https://res.cloudinary.com/dmjhwxcjh/image/upload/v1680059196/weather/theme_night_light_rain_fpokbo.jpg", themeDay: "https://res.cloudinary.com/dmjhwxcjh/image/upload/v1680054813/weather/theme_light_rain_dtyukx.jpg", dayIcon: "https://res.cloudinary.com/dmjhwxcjh/image/upload/v1678575908/weather/rain_aztazw.svg", nightIcon: "https://res.cloudinary.com/dmjhwxcjh/image/upload/v1678575908/weather/rain_aztazw.svg" },
    { code: 82, barColor: barColors.heavyBlue, description: "Rain Showers: Violent", aka: "Heavy Showers", themeNight: "https://res.cloudinary.com/dmjhwxcjh/image/upload/v1680054813/weather/theme_heavy_rain_uxyfaq.jpg", themeDay: "https://res.cloudinary.com/dmjhwxcjh/image/upload/v1680054813/weather/theme_heavy_rain_uxyfaq.jpg", dayIcon: "https://res.cloudinary.com/dmjhwxcjh/image/upload/v1678575908/weather/rain_aztazw.svg", nightIcon: "https://res.cloudinary.com/dmjhwxcjh/image/upload/v1678575908/weather/rain_aztazw.svg" },
    { code: 85, barColor: barColors.moderateBlue, description: "Snow Showers: Slight", aka: "Snow Showers", themeNight: "https://res.cloudinary.com/dmjhwxcjh/image/upload/v1680054813/weather/theme_snow_i63d8t.jpg", themeDay: "https://res.cloudinary.com/dmjhwxcjh/image/upload/v1680054813/weather/theme_snow_i63d8t.jpg", dayIcon: "https://res.cloudinary.com/dmjhwxcjh/image/upload/v1678575909/weather/snow_moderate_mtavja.svg", nightIcon: "https://res.cloudinary.com/dmjhwxcjh/image/upload/v1678575909/weather/snow_moderate_mtavja.svg" },
    { code: 86, barColor: barColors.heavyBlue, description: "Snow Showers: Heavy", aka: "Snow Showers", themeNight: "https://res.cloudinary.com/dmjhwxcjh/image/upload/v1680054813/weather/theme_snow_i63d8t.jpg", themeDay: "https://res.cloudinary.com/dmjhwxcjh/image/upload/v1680054813/weather/theme_snow_i63d8t.jpg", dayIcon: "https://res.cloudinary.com/dmjhwxcjh/image/upload/v1678575909/weather/snow_moderate_mtavja.svg", nightIcon: "https://res.cloudinary.com/dmjhwxcjh/image/upload/v1678575909/weather/snow_moderate_mtavja.svg" },
    { code: 95, barColor: barColors.moderateBlue, description: "Thunderstorm: Slight to Moderate", aka: "Thunderstorms", themeNight: "https://res.cloudinary.com/dmjhwxcjh/image/upload/v1680054813/weather/theme_thunderstorms_qnedmq.jpg", themeDay: "https://res.cloudinary.com/dmjhwxcjh/image/upload/v1680054813/weather/theme_thunderstorms_qnedmq.jpg", dayIcon: "https://res.cloudinary.com/dmjhwxcjh/image/upload/v1678575909/weather/thunderstorms_light_moderate_wakc6b.svg", nightIcon: "https://res.cloudinary.com/dmjhwxcjh/image/upload/v1678575909/weather/thunderstorms_light_moderate_wakc6b.svg" },
    { code: 96, barColor: barColors.moderateBlue, description: "Thunderstorm: Slight Hail", aka: "Hail", themeNight: "https://res.cloudinary.com/dmjhwxcjh/image/upload/v1680054813/weather/theme_hail_wbfilp.jpg", themeDay: "https://res.cloudinary.com/dmjhwxcjh/image/upload/v1680054813/weather/theme_hail_wbfilp.jpg", dayIcon: "https://res.cloudinary.com/dmjhwxcjh/image/upload/v1678575909/weather/thunderstorms_heavy_dzdshj.svg", nightIcon: "https://res.cloudinary.com/dmjhwxcjh/image/upload/v1678575909/weather/thunderstorms_heavy_dzdshj.svg" },
    { code: 99, barColor: barColors.heavyBlue, description: "Thunderstorm: Heavy Hail", aka: "Hail", themeNight: "https://res.cloudinary.com/dmjhwxcjh/image/upload/v1680054813/weather/theme_hail_wbfilp.jpg", themeDay: "https://res.cloudinary.com/dmjhwxcjh/image/upload/v1680054813/weather/theme_hail_wbfilp.jpg", dayIcon: "https://res.cloudinary.com/dmjhwxcjh/image/upload/v1678575909/weather/thunderstorms_heavy_dzdshj.svg", nightIcon: "https://res.cloudinary.com/dmjhwxcjh/image/upload/v1678575909/weather/thunderstorms_heavy_dzdshj.svg" }    
];

export const weatherDescription = (num) => {
    let codeDescription = (wCodes.find(c => c.code === num)).description;
    return codeDescription;
}

export const weatherAka = (num) => {
    let codeAka = (wCodes.find(c => c.code === num)).aka;
    return codeAka;
}

export const weatherBarColor = (num) => {
    let codeBarColor = (wCodes.find(c => c.code === num)).barColor;
    return codeBarColor;
}

export const weatherDailyBarIcon = (num) => {
    let codeBarIcon = (wCodes.find(c => c.code === num)).dayIcon;
    return codeBarIcon;
}

export const weatherIcon = (num, time, sunrise, sunset) => {
    let don;
    (time >= sunrise && time <= sunset) ? don = 'day' : don = 'night'; 
    let codeIcon = (don === 'day') ? (wCodes.find(c => c.code === num)).dayIcon : (wCodes.find(c => c.code === num)).nightIcon;
    return codeIcon;
}

export const weatherTheme = (num, time, sunrise, sunset) => {
    let don;
    (time >= sunrise && time <= sunset) ? don = 'day' : don = 'night'; 
    let codeTheme = (don === 'day') ? (wCodes.find(c => c.code === num)).themeDay : (wCodes.find(c => c.code === num)).themeNight;
    return codeTheme;
}